overwrite: true

# schema: ../doc/schema.graphql
schema: http://localhost:5000/graphql?sdl
generates:
  ./src/api/models.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
