version: "3.7"
services:
    backend:
        build:
            dockerfile: ./Dockerfile
            context: ./backend
        ports:
            - "5000:5000"
        environment:
            - BUILD_MODE=development
            - ApplicationInsights__InstrumentationKey
            - AzureAd__ClientSecret
            - Database__ConnectionString
