overwrite: true

schema:
  - http://localhost:5000/graphql?sdl
generates:
  ./src/api/models.ts:
    plugins:
      - "typescript"
    config:
      # Disallow Maybe to be null
      maybeValue: T
      sort: false
