parameters:
    - name: dependsOn
    - name: envshortname

stages:
    - stage: ${{ parameters.envshortname }}_Environment
      dependsOn: # this stage runs after buildfrontend and buildbackend
          - ${{ parameters.dependsOn }}
      jobs:
          - deployment: Enable${{ parameters.envshortname }}Environment
            environment: ${{ parameters.envshortname }}
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - bash: |
                                  echo '##vso[task.setvariable variable=${{ parameters.envshortname }}Approval;]true'
