trigger:
    branches:
        include:
            - master
    tags:
        include:
            - v*
    paths:
        exclude:
            - /*
pool:
    vmImage: "ubuntu-latest"

stages:
    - template: templates/stage-build.yml
      parameters:
          workSpace: $(Pipeline.Workspace)
          buildId: $(Build.BuildId)
          dt_tenant: $(dt_tenant)
          dt_password: $(dt_password)
          dt_url: $(dt_url)
          sourcesDirectory: $(Build.SourcesDirectory)
          name: "Build_applications"

    - template: templates/stage-deploy.yml
      parameters:
          name: Deploy_CI
          envshortname: ci
          envfullname: CI
          fusionToken: "$(tokenResource)"
          fusionBundlePath: "$(Agent.BuildDirectory)/bmt.zip"
          portalUrl: "https://pro-s-portal-ci.azurewebsites.net"
          buildId: $(Build.BuildId)
          radixToken: $(RadixToken)
          branch: master
          DBContext: $(dbContextDev)

    - template: templates/stage-deploy.yml
      parameters:
          name: Deploy_QA
          envshortname: qa
          envfullname: QA
          fusionToken: "$(tokenResource)"
          fusionBundlePath: "$(Agent.BuildDirectory)/bmt.zip"
          portalUrl: "https://pro-s-portal-fqa.azurewebsites.net/"
          buildId: $(Build.BuildId)
          radixToken: $(RadixToken)
          branch: qa
          DBContext: $(dbContextQa)

    - template: templates/stage-deploy.yml
      parameters:
          name: Deploy_Prod
          envshortname: prod
          envfullname: Production
          fusionToken: "$(tokenResourceProd)"
          fusionBundlePath: "$(Agent.BuildDirectory)/bmt.zip"
          portalUrl: "https://pro-s-portal-fprd.azurewebsites.net"
          buildId: $(Build.BuildId)
          radixToken: $(RadixToken)
          branch: prod
          DBContext: $(dbContextProd)
