trigger:
    - master

pr:
    - master

pool:
    vmImage: "ubuntu-latest"

jobs:
    - job: Build_API
      steps:
          - task: UseDotNet@2
            inputs:
                packageType: "sdk"
                version: "6.0.x"
                includePreviewVersions: true # Required for preview versions
          - task: DotNetCoreCLI@2
            name: Build_Backend
            inputs:
                command: "build"
                workingDirectory: "backend/api"

    - job: Build_Frontend
      steps:
          - task: NodeTool@0
            inputs:
                versionSpec: "16.x"
          - task: Npm@1
            inputs:
                command: "install"
                workingDir: "frontend"
          - task: Npm@1
            inputs:
                command: "custom"
                workingDir: "frontend"
                customCommand: "run-script build"

    - job: Test_Backend
      steps:
          - task: UseDotNet@2
            inputs:
                packageType: "sdk"
                version: "6.0.x"
                includePreviewVersions: true # Required for preview versions
          - task: DotNetCoreCLI@2
            name: Run_Backend_Tests
            inputs:
                command: "test"
                projects: "backend/tests/tests.csproj"

    - job: Test_Frontend
      steps:
          - task: NodeTool@0
            inputs:
                versionSpec: "16.x"
          - task: Npm@1
            name: Install
            inputs:
                command: "install"
                workingDir: "frontend"
          - task: Npm@1
            name: Run_Frontend_Tests
            inputs:
                command: "custom"
                workingDir: "frontend"
                customCommand: "test"
