trigger:
    branches:
        include:
            - master
    tags:
        include:
            - v*
    paths:
        exclude:
            - /*
pool:
    vmImage: "ubuntu-latest"

variables:
    - group: bmt-key-vault
    - group: bmt-variables

stages:
    - template: templates/stage-build.yml
      parameters:
          workSpace: $(Pipeline.Workspace)
          buildId: $(Build.BuildId)
          azAppConfig: $(azureAppConfig)
          sourcesDirectory: $(Build.SourcesDirectory)
          name: "Build_applications"

    - template: templates/stage-deploy.yml
      parameters:
          name: Deploy_CI
          fusionEnvironment: ci
          envshortname: ci
          envfullname: CI
          FusionEnvId: $(fusionClientIdDev)
          buildId: $(Build.BuildId)
          radixToken: $(RadixToken)
          branch: master
          DBContext: $(dbContextDev)
          SpAzureClientId: $(SpPreProdAzureClientId)
          SpAzureClientSecret: $(SpPreProdAzureClientSecret)
          AzureTenantId: $(SpAzureTenantId)

    - template: templates/stage-deploy.yml
      parameters:
          name: Deploy_QA
          fusionEnvironment: fqa
          envshortname: qa
          envfullname: QA
          FusionEnvId: $(fusionClientIdDev)
          buildId: $(Build.BuildId)
          radixToken: $(RadixToken)
          branch: master
          DBContext: $(dbContextQa)
          SpAzureClientId: $(SpPreProdAzureClientId)
          SpAzureClientSecret: $(SpPreProdAzureClientSecret)
          AzureTenantId: $(SpAzureTenantId)

    - template: templates/stage-deploy.yml
      parameters:
          name: Deploy_Prod
          fusionEnvironment: fprd
          envshortname: prod
          envfullname: Production
          FusionEnvId: $(fusionClientIdProd)
          buildId: $(Build.BuildId)
          radixToken: $(RadixToken)
          branch: master
          DBContext: $(dbContextProd)
          SpAzureClientId: $(SpPreProdAzureClientId)
          SpAzureClientSecret: $(SpPreProdAzureClientSecret)
          AzureTenantId: $(SpAzureTenantId)
