# Update environment secrets in Radix

trigger:
  - secret-rotation

schedules:
  - cron: "0 0 1 * *"
    displayName: Montly update radix secrets
    branches:
      include:
      - master
    always: true

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: bmt-key-vault
  - group: bmt-variables

jobs:
  - job: "Update_Radix_secrets"
    strategy:
      matrix:
        dev:
          DB_CONTEXT: $(dbContextDev)
          ENV_NAME: dev
        qa:
          DB_CONTEXT: $(dbContextQa)
          ENV_NAME: qa
        pr:
          DB_CONTEXT: $(dbContextDev)
          ENV_NAME: pr
        prod:
          DB_CONTEXT: $(dbContextProd)
          ENV_NAME: prod
    steps:
      - template: templates/step-update-radix-secret.yml
        parameters:
          envName: $(ENV_NAME)
          componentName: "backend"
          secretName: "Database__ConnectionString"
          secretValue: "$(DB_CONTEXT)"
      - template: templates/step-update-radix-secret.yml
        parameters:
          envName: $(ENV_NAME)
          componentName: "backend-acr"
          secretName: "Database__ConnectionString"
          secretValue: $(DB_CONTEXT)
      - template: templates/step-update-radix-secret.yml
        parameters:
          envName: $(ENV_NAME)
          componentName: "backend"
          secretName: "AzureAd__ClientSecret"
          secretValue: $(AzureAdClientSecret)
      - template: templates/step-update-radix-secret.yml
        parameters:
          envName: $(ENV_NAME)
          componentName: "backend-acr"
          secretName: "AzureAd__ClientSecret"
          secretValue: $(AzureAdClientSecret)
      - script: |
          url='https://api.radix.equinor.com/api/v1/applications/fusion-bmt/environments/$(ENV_NAME)/restart'
          authHeader='Authorization: Bearer $(radixToken)'
          curl -f -X POST --url "$url" -H "$authHeader"
          echo $url
        displayName: "Restart Radix $(ENV_NAME)"
